# Generated by Django 3.2.7 on 2021-11-25 20:35

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(default='14 dígitos', max_length=14)),
                ('razaoSocial', models.CharField(default=' ', max_length=10)),
                ('email', models.CharField(default=' ', max_length=50)),
                ('cidade', models.CharField(default=' ', max_length=20)),
                ('estado', models.CharField(default='Ex: SP', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=14)),
                ('nascimento', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=20)),
                ('nivel', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=6)),
                ('semana', multiselectfield.db.fields.MultiSelectField(choices=[('segunda', 'seg'), ('terca', 'ter'), ('quarta', 'qua'), ('quinta', 'quinta-feira'), ('sexta', 'sexta-feira'), ('sabado', 'sábado'), ('domingo', 'domingo'), ('desistente', 'desistente')], max_length=59)),
                ('pagamento', models.CharField(max_length=10)),
                ('obervacao', models.TextField(max_length=1000)),
                ('horario', models.TextField(max_length=1000)),
            ],
        ),
    ]
